name: 'npm audit'
description: 'Automatically fail builds with high severity vulnerabilities'
inputs:
  fail-on:
    description: 'Severity to fail on'
    required: true
    default: 'high'
runs:
  using: 'node12'
  main: 'dist/index.js'