on: [push, pull_request]

jobs:
  npm_audit_job:
    runs-on: ubuntu-latest
    name: A job to scan for NPM vulnerabilities
    steps:
      - name: npm audit
        id: audit
        uses: nmcginn/npm-audit-gh-action@v1.0
        with:
          fail-on: 'high'
